name = "dopamine-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "DOPAMINE_KV"
id = "87ca3bca728943c9bd81d93320dede26"

[vars]
GEMINI_API_KEY = "AIzaSyBNiRvw7opgBRu3cfOw6S8SwOQB6zK7OJ0"
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "AIzaSyDbslFWVHP3f8D42vJ5Uh1RwBJk13FRaes"
